name: protrek
channels:
  - defaults
  - pytorch
  - anaconda
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=openblas
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.12.2=h06a4308_0
  - cuda-cudart=12.8.90=hbdd6827_0
  - cuda-cudart_linux-64=12.8.90=hd1a145a_0
  - cuda-nvrtc=12.8.93=hbdd6827_1
  - cuda-version=12.8=h30beaf8_3
  - expat=2.7.3=h7354ed3_4
  - intel-openmp=2023.0.0=h9e868ea_25371
  - ld_impl_linux-64=2.44=h153f514_2
  - libcublas=12.8.4.1=hbdd6827_1
  - libexpat=2.7.3=h7354ed3_4
  - libfaiss=1.8.0=h046e95b_0_cuda12.1.1
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgfortran=15.2.0=h166f726_7
  - libgfortran-ng=15.2.0=h166f726_7
  - libgfortran5=15.2.0=hc633d37_7
  - libgomp=15.2.0=h4751f2c_7
  - libnsl=2.0.0=h5eee18b_0
  - libopenblas=0.3.30=h46f56fc_2
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - mkl=2023.1.0=h213fc3f_46344
  - ncurses=6.5=h7934f7d_0
  - numpy=1.26.4=py310hc213724_1
  - numpy-base=1.26.4=py310hf387b04_1
  - openssl=3.0.18=hd6dcaed_0
  - packaging=25.0=py310h06a4308_1
  - pip=25.3=pyhc872135_0
  - pthread-stubs=0.3=h0ce48e5_1
  - pysocks=1.7.1=py310h06a4308_1
  - python=3.10.19=h6fa692b_0
  - readline=8.3=hc2a1206_0
  - setuptools=80.9.0=py310h06a4308_0
  - sqlite=3.51.1=he0a8d7e_0
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.15=h54e0aa7_0
  - wheel=0.45.1=py310h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - aiofiles==23.2.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.3
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - anyio==4.12.1
      - async-timeout==5.0.1
      - attrs==25.4.0
      - biopython==1.83
      - certifi==2026.1.4
      - charset-normalizer==3.4.4
      - click==8.3.1
      - cmake==4.2.1
      - contourpy==1.3.2
      - cycler==0.12.1
      - dill==0.4.0
      - easydict==1.13
      - exceptiongroup==1.3.1
      - faiss-gpu==1.7.2
      - fastapi==0.112.4
      - ffmpy==1.0.0
      - filelock==3.20.2
      - fonttools==4.61.1
      - frozenlist==1.8.0
      - fsspec==2025.12.0
      - gradio==4.43.0
      - gradio-client==1.3.0
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.36.0
      - idna==3.11
      - importlib-resources==6.5.2
      - jinja2==3.1.6
      - joblib==1.5.3
      - kiwisolver==1.4.9
      - lightning-utilities==0.15.2
      - lit==18.1.8
      - lmdb==1.4.1
      - markdown-it-py==4.0.0
      - markupsafe==2.1.5
      - matplotlib==3.10.8
      - mdurl==0.1.2
      - mpmath==1.3.0
      - multidict==6.7.0
      - multiprocess==0.70.18
      - networkx==3.4.2
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cuda-cupti-cu11==11.7.101
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.2.10.91
      - nvidia-cusolver-cu11==11.4.0.1
      - nvidia-cusparse-cu11==11.7.4.91
      - nvidia-nccl-cu11==2.14.3
      - nvidia-nvtx-cu11==11.7.91
      - orjson==3.11.5
      - pandas==2.3.3
      - pillow==10.4.0
      - propcache==0.4.1
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pydub==0.25.1
      - pygments==2.19.2
      - pyparsing==3.3.1
      - pyspellchecker==0.8.2
      - python-dateutil==2.9.0.post0
      - python-multipart==0.0.21
      - pytorch-lightning==2.1.3
      - pytz==2025.2
      - pyyaml==6.0.3
      - regex==2025.11.3
      - requests==2.32.5
      - rich==14.2.0
      - ruff==0.14.10
      - scikit-learn==1.4.0
      - scipy==1.15.3
      - seaborn==0.13.2
      - semantic-version==2.10.0
      - shellingham==1.5.4
      - six==1.17.0
      - socksio==1.0.0
      - starlette==0.38.6
      - sympy==1.14.0
      - tabulate==0.9.0
      - threadpoolctl==3.6.0
      - tokenizers==0.13.3
      - tomlkit==0.12.0
      - torch==2.0.1
      - torchaudio==2.0.2
      - torchmetrics==0.9.3
      - torchvision==0.15.2
      - tqdm==4.67.1
      - transformers==4.28.0
      - triton==2.0.0
      - typer==0.21.1
      - typer-slim==0.21.1
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.3
      - urllib3==2.6.3
      - uvicorn==0.40.0
      - websockets==12.0
      - yarl==1.22.0
prefix: /home/dylan/miniconda/envs/protrek
